metadata module docs
DOV-Vlaanderen/geoserver pull request #43
Opened 2019-04-10 12:24 UTC by timothy-debock

2019-04-10 12:26 UTC, timothy-debock commented
eerste versie

2019-04-15 14:57 UTC, NielsCharlier commented
Lijkt me vrij volledig, buiten kleine opmerkingen van mij hier en daar. Een belangrijk stuk ontbreekt nog: automatische generatie van de catalogus en domeinen. (En hoe je dit expliciet moet configureren: aan de hand van het vaste ingebouwde type "featureAttribute")

2019-04-15 14:59 UTC, NielsCharlier requested changes

2019-04-15 14:59 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/configuration.rst
> +
configuration

2019-04-15 14:59 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/user.rst
> +
Dit klopt niet denk ik, alleen de gemapte velden worden gewist/overschreven door de import.

2019-04-15 14:59 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/user.rst
> +This will override any values in fields that are not a list.
Idem, alleen als de velden in de template zitten.

2019-04-15 14:59 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/user.rst
> +
Misschien duidelijk maken dat de prioriteit = de volgorde in de tabel.

2019-04-15 14:59 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/user.rst
> +
En eerder dan "shown" zou ik zeggen "picked"

2019-04-15 14:59 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/user.rst
> +
Mag iets uitgebreider en duidelijker. Duidelijk maken dat aanpassingen op het template-overzich scherm (verwijderen en veranderen van volgorde) vereisen dat je moet opslaan. Hier mag ook wel een prentje bij.

2019-04-15 14:59 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/uiconfiguration.rst
> +.. warning:: TODO
???

2019-04-15 14:59 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/user.rst
> +For Fields that are a list the values from the template will be added as read only fields. The duplicate values in list will be removed if there are any.
Ook single velden zijn read-only wanneer ze uit template komen. Best in een aparte zin duidelijk maken.

2019-04-15 14:59 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/configuration.rst
> +
Alles hieronder moet in een aparte tutorial, er mag hier een link naartoe geplaatst worden (maar toch zeker ook vanaf de index)

2019-04-16 11:48 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/uiconfiguration.rst
> +
zou hier voor de volledigheid ook al niet "values" en "typename" moeten vermeld worden

2019-04-16 11:51 UTC, NielsCharlier requested changes

2019-04-16 11:51 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/uiconfiguration.rst
> +
In principe kunnen de waarden van een DERIVED veld ook via "values" worden gespecificeerd. De volgorde moet dan overeenkomen met de volgorde van het veld waarvan afgeleid wordt.

2019-04-16 11:51 UTC, NielsCharlier commented on doc/en/user/source/community/metadata/uiconfiguration.rst
> +
In principe kan zo een CSV ook meer dan twee kolommen bevatten, wat je nodig hebt als je meer dan een veld zou afleiden van ehtzelfde veld

2019-04-16 13:38 UTC, timothy-debock commented on doc/en/user/source/community/metadata/uiconfiguration.rst
> +.. warning:: TODO
Dat was om die feature catalog te beschrijving, maar ik heb zelf geen idee wat die doet :)
typename: featureAttribute

2019-04-18 11:08 UTC, merged